- name: Ensure base directory exists
  file: path={{ ssl_cert_file_base_dir }} state=directory

- name: Check if certificate exists
  stat: path={{ ssl_cert_file.cert }}
  register: stat_cert_result

- name: Check if intermediate certificate chain exists
  stat:
    path: "{{ ssl_cert_file.chain }}"
  register: stat_intermediate_chain_result

- name: Read intermediate certificate chain
  when: stat_intermediate_chain_result.stat.exists
  block:
  - name: Read intermediate certificate chain
    slurp:
      src: "{{ ssl_cert_file.chain }}"
    register: slurp_intermediate_chain_result
  - name: Set intermediate certificate chain as fact
    set_fact:
      ssl_intermediate_cert_data: "{{ slurp_intermediate_chain_result.content | b64decode }}"

- name: Set certificate reading facts
  set_fact:
    ssl_cert_exists: "{{ stat_cert_result.stat.exists }}"
    ssl_intermediate_cert_exists: "{{ stat_intermediate_chain_result.stat.exists }}"
