- name: Save certificate files
  when: not ssl_cert_exists
  block:
  - name: Save key
    copy:
      dest: "{{ ssl_cert_file.key }}"
      mode: 0600
      content: "{{ ssl_cert_key_data }}"
  - name: Save certificate
    copy:
      dest: "{{ ssl_cert_file.cert }}"
      content: "{{ ssl_cert_data }}"

- name: Save intermediate certificate chain
  when: not ssl_intermediate_cert_exists
  copy:
    dest: "{{ ssl_cert_file.chain }}"
    content: "{{ ssl_cert_data + ssl_intermediate_cert_data if ssl_cert_type == 'intermediate' else ssl_intermediate_cert_data }}"
