- name: Include read tasks
  include: "{{ ssl_cert_storage }}/read-certs.yml"

- name: Include CA tasks
  include: ca-{{ ssl_ca_type }}.yml

- name: Include write tasks
  include: "{{ ssl_cert_storage }}/write-certs.yml"
