- name: Check if secret exists
  k8s_facts:
    kubeconfig: /etc/kubernetes/kubeconfig-local
    kind: Secret
    name: "{{ ssl_cert_name }}"
    namespace: "{{ ssl_cert_k8s_secret_namespace }}"
  register: k8s_result
- name: Set certificate reading facts
  set_fact:
    ssl_cert_exists: "{{ k8s_result.resources|length > 0 }}"
    ssl_intermediate_cert_exists: "{{ k8s_result.resources|length > 0 }}"
- name: Set intermediate certificate chain fact
  when: ssl_intermediate_cert_exists
  set_fact:
    ssl_intermediate_cert_data: "{{ k8s_result.resources[0].data['ca.crt'] | b64decode }}"
