- name: Save secret
  when: not ssl_cert_exists
  k8s:
    kubeconfig: /etc/kubernetes/kubeconfig-local
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/tls
      metadata:
        name: "{{ ssl_cert_k8s_secret_name }}"
        namespace: "{{ ssl_cert_k8s_secret_namespace }}"
      data:
        ca.crt: "{{ ssl_intermediate_cert_data | b64encode }}"
        tls.crt: "{{ ssl_cert_data | b64encode }}"
        tls.key: "{{ ssl_cert_key_data | b64encode }}"
